name: linkage

dependencies:
    - base
    - gloss
    - fgl
    - lens
    - vector
    - nonlinear-optimization-ad
    - ad

executable:
    main: linkage.hs
    source-dirs: .

default-extensions:
    - OverloadedStrings
